services:

  php:
    build:
      context: "."
      dockerfile: "Dockerfile"
    restart: unless-stopped
    #ports:
    #   - 9000:9000
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php-fpm.ini:/opt/bitnami/php/etc/php-fpm.conf
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini-production
      - ./docker/php-fpm/php-dev.ini:/usr/local/etc/php/php.ini-development
    environment:
      PHP_UPLOAD_MAX_FILESIZE: '2000M'
      PHP_POST_MAX_SIZE: '2000M'
      PHP_MAX_EXECUTION_TIME: '300'
      PHP_MEMORY_LIMIT: '50000M'
    expose:
      - 9000
    networks:
    #  - public_network
      - internal_network
    deploy:
      mode: replicated
      replicas: 2

    #depends_on:
    #    - nginx
  nginx:
    image: nginx:1.27.0
    restart: unless-stopped
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./:/var/www/html
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/html:/var/www/certbot
    depends_on:
      - php
    environment:
      DOMAIN_NAME: superzaki.com
    networks:
      - internal_network
      - public_network

  db:
    image: mysql:8.0.36
    restart: unless-stopped
    ports:
      - "${DB_PORT-3306}:3307"
    volumes:
      -  /mnt/blockstorage/mysql:/var/lib/mysql_docker
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      #MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - internal_network

  composer:
    image: composer
    volumes:
      - ./docker/php-composer/entrypoint.sh:/entrypoint.sh
      - ./:/var/www/html
      - ./docker/php-composer/.composer_json_hash:/var/www/composer_json_hash/.composer_json_hash
    working_dir: /var/www/html
    entrypoint: /bin/sh -c '/entrypoint.sh'
    environment:
      COMPOSER_ALLOW_SUPERUSER: '1'
    depends_on:
      - php
      - nginx

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/entrypoint.sh:/entrypoint.sh
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/html:/var/www/certbot
      - ./docker/nginx/site.conf:/var/www/nginx/site.conf
      - ./docker/nginx/ssl:/var/www/nginx/ssl
    environment:
      - APP_URL=${APP_URL}
      - DOMAIN_NAME=superzaki.com
    entrypoint: /bin/sh -c '/entrypoint.sh'
    depends_on:
      - nginx
    restart: "no"


networks:
  public_network:
     driver: bridge

  internal_network:
     internal: true


#networks:
#  network: